In [1]:
import pandas as pd
import numpy as np

In [11]:
# 1、读取数据
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']

data = pd.read_csv(path, names=column_name)

In [12]:
data

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [13]:
data.isnull().any()

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [29]:
# 处理缺失值 将？替换为nan
data=data.replace(to_replace="?",value=np.nan)
data.dropna(inplace=True)

In [30]:
data.isnull().any()

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [31]:
# 划分数据集
from sklearn.model_selection import train_test_split

In [32]:
x=data.iloc[:,1:-1] 
y=data["Class"] # 目标值

In [33]:
x.head()

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses
0,5,1,1,1,2,1,3,1,1
1,5,4,4,5,7,10,3,2,1
2,3,1,1,1,2,2,3,1,1
3,6,8,8,1,3,4,3,7,1
4,4,1,1,3,2,1,3,1,1

In [34]:
y

0      2
1      2
2      2
3      2
4      2
      ..
694    2
695    2
696    4
697    4
698    4
Name: Class, Length: 683, dtype: int64

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=22)

In [36]:
from  sklearn.preprocessing import StandardScaler # 标准化

In [37]:
transfer=StandardScaler()
x_train=transfer.fit_transform(x_train)
x_test=transfer.transform(x_test)

In [41]:
#  预估器
from sklearn.linear_model import LogisticRegression # 逻辑回归

In [39]:
estimator=LogisticRegression()
estimator.fit(x_train,y_train)

LogisticRegression()

In [45]:
from sklearn.metrics import mean_squared_error

In [50]:
print("权重系数：\n", estimator.coef_)
print("偏置：\n", estimator.intercept_)
y_predict=estimator.predict(x_test)
print("y_predict:\n",y_predict)
print("t_test:\n",y_test)
print("真实值与预测值对比:\n",y_test==y_predict)
error=mean_squared_error(y_test,y_predict)
print("均方误差：\n",error)
socre=estimator.score(x_test,y_test)
print("准确率：\n",socre)

权重系数：
 [[1.19777169 0.10877967 0.73209957 0.60323232 0.12122898 1.48162508
  0.75112762 0.79980762 0.82133788]]
偏置：
 [-1.0749105]
y_predict:
 [2 4 4 2 2 2 2 2 2 2 2 2 2 4 2 2 4 4 4 2 4 2 4 4 4 2 4 2 2 2 2 2 4 2 2 2 4
 2 2 2 2 4 2 4 4 4 4 2 4 4 2 2 2 2 2 4 2 2 2 2 4 4 4 4 2 4 2 2 4 2 2 2 2 4
 2 2 2 2 2 2 4 4 4 2 4 4 4 4 2 2 2 4 2 4 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4 4 2
 2 2 2 4 2 2 2 2 2 2 4 2 4 2 2 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 2 2 2 4 2 4
 2 2 4 4 4 2 2 4 4 2 4 4 2 2 2 2 2 4 4 2 2 2 4]
t_test:
 389    2
32     4
272    4
655    2
271    2
      ..
296    2
585    2
256    2
43     4
691    4
Name: Class, Length: 171, dtype: int64
真实值与预测值对比:
 389     True
32      True
272     True
655     True
271     True
       ...
296    False
585     True
256     True
43     False
691     True
Name: Class, Length: 171, dtype: bool
均方误差：
 0.0935672514619883
准确率：
 0.9766081871345029